# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2681549dd3867b630f162f3ead5ec41b4eb491fef55c114363564f95b2ee46fed9b8b94e73fc3ebd6f7a2f36fbf5810a81cf843fab20b835f5b7a2c6628c2ebd

test:
  secret_key_base: 122e548a29f50ff82240b4e6a3f91edb98be9b2fb47fa13fad6df87cef918a7e3bad77e2cf71f8e106ab3f0f87305a6494a32bba6a9c863cd50d5093d033c046

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
